version: '3.9'
services:
  redis:
    image: redis:6.2.5-alpine
    container_name: redis
    restart:  unless-stopped
    command: redis-server --requirepass distributelockstudy
    volumes:
      - redis_data:/data
    ports:
      - "6400:6379"
volumes:
  redis_data:
